import { marked } from 'marked';
import TurndownService from 'turndown';

/**
 * Normalizes any markdown checkboxes "- [ ]" / "- [x]" into simple bullets "- ".
 * Needed for already-saved summaries (old format) and for any output where
 * the model still uses checkboxes despite the updated prompt.
 */
export function normalizeActionItems(markdown: string): string {
  return markdown.replace(/^(\s*)[-*]\s+\[[ xX]\]\s+/gm, '$1- ');
}

// HTML -> Markdown (to save what the user writes in the visual editor)
const turndown = new TurndownService({
  headingStyle: 'atx',        // # Heading
  bulletListMarker: '-',
  codeBlockStyle: 'fenced',
});

// Preserves Action Items checkboxes in the HTML -> Markdown round-trip.
// Without this rule turndown drops the <input type="checkbox"> and
// "- [ ] task" becomes a plain "- task", losing the checkbox.
// Handles two checkbox formats:
//  - <input type="checkbox"> generated by `marked` from the original markdown
//  - <li data-list="checked|unchecked"> generated by the Quill editor
function taskState(node: HTMLElement): { isTask: boolean; checked: boolean } {
  const dataList = node.getAttribute('data-list');
  if (dataList === 'checked') return { isTask: true, checked: true };
  if (dataList === 'unchecked') return { isTask: true, checked: false };
  const checkbox = node.querySelector('input[type="checkbox"]');
  if (checkbox) {
    return { isTask: true, checked: checkbox.hasAttribute('checked') || (checkbox as HTMLInputElement).checked };
  }
  return { isTask: false, checked: false };
}

turndown.addRule('taskListItems', {
  filter: (node) => node.nodeName === 'LI' && taskState(node as HTMLElement).isTask,
  replacement: (content, node) => {
    const { checked } = taskState(node as HTMLElement);
    const text = content.replace(/^\s+/, '').replace(/\n/g, ' ').trim();
    return `- [${checked ? 'x' : ' '}] ${text}\n`;
  },
});

/** Converts the summary markdown to HTML, for the visual editor (WYSIWYG). */
export function markdownToHtml(markdown: string): string {
  const html = marked.parse(markdown, { async: false }) as string;
  // marked produces <li><input type="checkbox"> ...</li>, but the Quill editor
  // uses <li data-list="checked|unchecked">. Convert so checkboxes aren't lost.
  return html.replace(
    /<li>\s*<input([^>]*)>\s*/g,
    (_m, attrs) => `<li data-list="${/checked/.test(attrs) ? 'checked' : 'unchecked'}">`
  );
}

/** Converts the editor HTML back to markdown, for saving/export/PDF. */
export function htmlToMarkdown(html: string): string {
  return turndown.turndown(html).trim();
}

/**
 * Converts markdown to clean readable plain text (.txt):
 * no #, **, [], just clean text with bulleted lists.
 */
export function markdownToPlainText(markdown: string): string {
  return markdown
    .split('\n')
    .map(line => {
      let l = line;
      l = l.replace(/^#{1,6}\s+/, '');                 // headings: strip #
      l = l.replace(/^>\s?/, '');                       // quotes: strip >
      l = l.replace(/^(\s*)[-*]\s+\[[ xX]\]\s+/, '$1• '); // checkbox -> •
      l = l.replace(/^(\s*)[-*]\s+/, '$1• ');           // bullet -> •
      l = l.replace(/\*\*([^*]+)\*\*/g, '$1');          // **bold** -> text
      l = l.replace(/\*([^*]+)\*/g, '$1');              // *italic* -> text
      l = l.replace(/`([^`]+)`/g, '$1');                // `code` -> text
      l = l.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)'); // [text](url) -> text (url)
      return l;
    })
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')                         // at most one blank line
    .trim();
}
